### PR TITLE
Clamp framebuffer texture to avoid edge pixels bleeding

### PR DESCRIPTION
**Pull request by popcornmix**
Avoids wrap like white line at top of fire shader

### CODE REVIEW

**Review by AlwinEsch — APPROVED** [review]
Looks good and will test it later

**Comment by AlwinEsch** [comment]
Maybe then also good to add here https://github.com/xbmc/visualization.shadertoy/blob/Matrix/src/main.cpp#L638

This have mostly the same code as here.

**Comment by popcornmix** [comment]
Added https://github.com/xbmc/visualization.shadertoy/pull/53

**Comment by popcornmix** [comment]
I'm going to guess the jenkins failure is unrelated.

**Comment by AlwinEsch** [comment]
I bring in later, want to have this stupid vfs.rar problems fixed asap before.

**Pull request merged**
