### PR TITLE
Add shaders from popcornmix addon

### PR DESCRIPTION
**Pull request by popcornmix**
This screensaver addon supercedes the popcornmix one, but there are a few nice shaders that are missing and run well on limited hardware.

These all run fine on Pi1 (with firmware GL) and Pi4 (with mesa GL) so should run on most devices.

### CODE REVIEW

**Comment by popcornmix** [comment]
Note: because of the pain in reordering the list of shaders, I've added these to the end of the list for testing. Once agreed I'll reorder the whole list before merging.

**Review by AlwinEsch — APPROVED** [review]
I will test it, yes thats on settings.xml is a pain in the ass.

Think to add a new interface function in future, that there on settings is only a button where open a selection dialog where created from addon, so that only the C++ list is present.

**Comment by popcornmix** [comment]
Generating the settings list from cpp would be great (I looked into it long ago, but didn't find a way of doing it with existing apis).

**Comment by AlwinEsch** [comment]
On the begin 10 years ago this was partly possible, but with lack of use and not safe enough was it removed. There it was possible to give the whole settings.xml via code call.

Have done runtime test and looks good :+1:

**Comment by popcornmix** [comment]
Okay - let me reorder list.

**Comment by popcornmix** [comment]
Reordered alphabetically. Feel free to squash when merging.

**Pull request merged**
